// <copyright file="TranslationConfiguration.cs" company="Allied Bits Ltd.">
//
// Copyright 2025 Allied Bits Ltd.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// </copyright>

using System.Reflection;

#if GENERATOR
namespace Tlumach.Generator
#else
namespace Tlumach.Base
#endif
{
    /// <summary>
    /// Contains the configuration built when parsing source files and passed to the translation manager by the translation unit.
    /// </summary>
    public class TranslationConfiguration
    {
#pragma warning disable CA1707 // Identifiers should not contain underscores

        /// <summary>
        /// The name of the default file (the one that will be loaded by default).
        /// </summary>
        public const string KEY_DEFAULT_FILE = "defaultFile";

        /// <summary>
        /// The name of the locale of the text in the default file.
        /// </summary>
        public const string KEY_DEFAULT_LOCALE = "defaultLocale";

        /// <summary>
        /// The name of the namespace that the generator puts to the generated source code.
        /// </summary>
        public const string KEY_GENERATED_NAMESPACE = "generatedNamespace";

        /// <summary>
        /// The name of the class that the generator puts to the generated source code.
        /// </summary>
        public const string KEY_GENERATED_CLASS = "generatedClass";

        /// <summary>
        /// The name of the class that the generator puts to the generated source code.
        /// </summary>
        public const string KEY_TEXT_PROCESSING_MODE = "textProcessingMode";

        /// <summary>
        /// The optional notation to specify the file, from which all translations not listed specifically are loaded. This values gets converted to "other" in the code but may be used for clarity in the configuration files.
        /// </summary>
        public const string KEY_TRANSLATION_ASTERISK = "*";

        /// <summary>
        /// The optional notation to specify the file, from which all translations not listed specifically are loaded.
        /// </summary>
        public const string KEY_TRANSLATION_OTHER = "other";

        /// <summary>
        /// The name of the translations section in the configuration file.
        /// </summary>
        public const string KEY_SECTION_TRANSLATIONS = "translations";

        /// <summary>
        /// The name of an element in the translations section in the configuration file (XML only).
        /// </summary>
        public const string KEY_LOCALE = "locale";

        /// <summary>
        /// The name of the "name" attribute in the translations section in the configuration file (XML only).
        /// </summary>
        public const string KEY_ATTR_NAME = "name";

        /// <summary>
        /// The name of the translations section in the configuration file suffixed with a dot.
        /// </summary>
        public static readonly string KEY_SECTION_TRANSLATIONS_DOT = KEY_SECTION_TRANSLATIONS + ".";
#pragma warning restore CA1707 // Identifiers should not contain underscores

        public static TranslationConfiguration Empty { get; }

        /// <summary>
        /// Gets a reference to the assembly, in which the generated file resides.
        /// </summary>
        public Assembly? Assembly { get; }

        /// <summary>
        /// Gets a reference to the default file. The value may be a filename with or without a path, but it must include an extension, so that the proper parser can be selected.
        /// </summary>
        public string DefaultFile { get; }

        /// <summary>
        /// Gets the namespace, to which the generated class should belong.
        /// </summary>
        public string? Namespace { get; }

        /// <summary>
        /// Gets the name of the class that is generated by the generator.
        /// </summary>
        public string? ClassName { get; }

        /// <summary>
        /// Gets a locale of the default file, if the locale was present in this file.
        /// </summary>
        public string? DefaultFileLocale { get; }

        /// <summary>
        /// Gets the text processing mode used for parsing (it will be used for processing templates too).
        /// </summary>
        public TextFormat TextProcessingMode { get; }

        /// <summary>
        /// Gets the list of individual translation items covered by the configuration.
        /// This list may be empty or incomplete, in which case, the library will use heuristics to determine the filename to load the translation from.
        /// </summary>
        public Dictionary<string, string> Translations { get; } = [];

        /// <summary>
        /// Gets or sets the hint path that can be used when locating translation files.
        /// <para>When configuration is loaded by the constructors of the TranslationManager class, this property is set to whatever directory is specified in the configFile parameter of the constructor, but an application is free to change it.</para>
        /// <para>Another way to specify the hint is to set the TranslationsDirectory property of TranslationManager.</para>
        /// </summary>
        public string? DirectoryHint { get; set; }

        static TranslationConfiguration()
        {
            Empty = new();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TranslationConfiguration"/> class.
        /// <para>Usable by the code that does not use TranslationUnits.</para>
        /// </summary>
        /// <param name="assembly">An optional assembly that contains translations. May be empty if files are loaded from the disk.</param>
        /// <param name="defaultFile">a reference to the default file for the translation.</param>
        /// <param name="defaultFileLocale">The locale specified in the file (when supported by the file format).</param>
        /// <param name="textProcessingMode">specifies how the translation entries should be parsed to determine whether they contain placeholders and to replace these placeholders with real values. See <seealso cref="TextFormat"/> for details.</param>
        public TranslationConfiguration(Assembly? assembly, string defaultFile, string? defaultFileLocale, TextFormat textProcessingMode)
        {
            Assembly = assembly;
            DefaultFile = defaultFile;
            DefaultFileLocale = defaultFileLocale;
            TextProcessingMode = textProcessingMode;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TranslationConfiguration"/> class.
        /// <para>Used by configuration parsers.</para>
        /// </summary>
        /// <param name="assembly">An optional assembly that contains translations. May be empty if files are loaded from the disk.</param>
        /// <param name="defaultFile">a reference to the default file for the translation.</param>
        /// <param name="namespace">The namespace to which the class with generated translation units belongs.</param>
        /// <param name="className">The name of the class with generated translation units.</param>
        /// <param name="defaultFileLocale">The locale specified in the file (when supported by the file format).</param>
        /// <param name="textProcessingMode">specifies how the translation entries should be parsed to determine whether they contain placeholders and to replace these placeholders with real values. See <seealso cref="TextFormat"/> for details.</param>
        public TranslationConfiguration(Assembly? assembly, string defaultFile, string? @namespace, string? className, string? defaultFileLocale, TextFormat textProcessingMode)
        {
            Assembly = assembly;
            DefaultFile = defaultFile;
            DefaultFileLocale = defaultFileLocale;
            Namespace = @namespace;
            ClassName = className;
            TextProcessingMode = textProcessingMode;
        }

        private TranslationConfiguration()
        {
            DefaultFile = string.Empty;
        }

        public string GetEscapeModeFullName()
        {
            return typeof(TextFormat).Name + "." + TextProcessingMode.ToString();
        }
    }
}
